import antfu from "@antfu/eslint-config";

export default antfu({
  stylistic: {
    "quotes": "double",
    "semi": true,
    "comma-style": "last",
  },
  react: true,
  astro: true,
  ignores: [
    "dist",
  ],
}, {
  files: ["src/container.mjs", "src/index.ts"],
  rules: {
    // Allow importing files generated by Astro
    "antfu/no-import-dist": ["off"],
  },
});
